#!/bin/bash

echo "::: higgs-ml [prediction]..."
echo "::: args:" $@

in=$1
trained=$2
out=$3

python python/higgs-pset-pred.py $in $trained $out || exit 1

echo "::: higgs-ml [prediction]... [ok]"
exit 0
